version: '3,7'

services:
  frontend:
    build:
      context: frontend
      target: prod
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_GOOGLE_CLIENT_SECRET=${VITE_GOOGLE_CLIENT_SECRET}
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    container_name: frontend
    networks: 
      - api
networks:
  api:
    driver: bridge